config/routes.rb
Lepra2::Application.routes.draw do
  get "lepra2/index"

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users, :controllers => { :registrations => "registrations" } 

  resources :symbol_lookups

  resources :assessments

  resources :reactions

  resources :staffs

  resources :clinics

  resources :contacts

  resources :personal_histories

  resources :people

  resources :remarks

  resources :locations

  resources :addresses

  root :to => 'lepra2#index'

end

app/models/person.rb
class Person < ActiveRecord::Base
  has_many :personal_histories, :order => 'date'  
  has_many :contacts
  has_many :assessments
  has_many :reactions
  has_many :addresses
  # has_many :locations, :through => addresses

  validates :name, :registration, :presence => true
  validates :name, :length => { :minimum => 4 }
  validates_numericality_of :year_of_birth, :only_integer => true, :message => "can only be whole number."
  YEAR = Time.now.year
  YEAR1 = YEAR - 105
  validates_inclusion_of :year_of_birth, :in => YEAR1..YEAR, :message => "can only be between #{YEAR1} and #{YEAR}."

  def show_name
    ret = name
    ret = 'unknown' if ret == nil
    ret += ' ('+nickname+')' if nickname and nickname != ''
    ret
  end

  # return Clinic object (FIXME)
  def clinic
    if contacts.size > 0
      return contacts.last.clinic_id
    end
    '?'
  end

  # return Address object, or nil
  def address
    if addresses.size > 0
      return addresses.last
    end
    nil
  end

  # return genders as M/F letter
  def gender
    (male ? 'M' : 'F')
  end

  # return village name
  def village
    if addresses.size > 0
      return addresses.last.village
    end
    'unknown location'
  end
 
  def self.search(search, is_anywhere = true, clinic_id)
    clinic_id = false # ignore for now
    if not search and not clinic_id
      find(:all, :limit => 100)
    else
      query1 = 'registration=? OR name LIKE ? OR nickname=?'
      registration1 = search
      name1 = "#{search}%"
      nickname1 = search
      if is_anywhere
        query1 = 'registration=? or name LIKE ? OR nickname LIKE ?'
        name1 = "%#{search}%"
        nickname1 = "#{search}%"
      end
      if clinic_id
        query1 += ' AND personal_histories.clinic_id=?'
        find(:all, :include => :personal_histories, :conditions => [ query1, registration1, name1, nickname1, clinic_id], :limit => 100)
      else
        find(:all, :conditions => [ query1, registration1, name1, nickname1], :limit => 100)
      end
    end
  end


end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  # GET /people
  # GET /people.json
  def index
    @people = Person.search(params[:search], params[:is_anywhere], params[:clinic_id])
  end

  def index2
    @people = Person.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @people }
    end
  end

  # GET /people/1
  # GET /people/1.json
  def show
    @person = Person.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @person }
    end
  end

  # GET /people/new
  # GET /people/new.json
  def new
    # update village, if there
    # params['village'] = nil
    @person = Person.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @person }
    end
  end

  # GET /people/1/edit
  def edit
    @person = Person.find(params[:id])
  end

  # POST /people
  # POST /people.json
  def create
    rec = params['person']
    rec.delete('village')
    @person = Person.new(params[:person])

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render json: @person, status: :created, location: @person }
      else
        format.html { render action: "new" }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /people/1
  # PUT /people/1.json
  def update
    @person = Person.find(params[:id])

    respond_to do |format|
      if @person.update_attributes(params[:person])
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person = Person.find(params[:id])
    @person.destroy

    respond_to do |format|
      format.html { redirect_to people_url }
      format.json { head :ok }
    end
  end
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/people/_form.html.erb
  <%= semantic_form_for @person do |f| %>
    <%= f.inputs %>
    <%= f.buttons :commit %>
    <%= f.input :created_at, :as => :string, :input_html => { :readonly => true } %>
    <%= f.input :updated_at, :as => :string, :input_html => { :readonly => true } %>
  <% end %>

app/views/people/_form.html.haml
%div.info
  The patient card contains unique information about a person that exists once only in the database

%div
  #form
    = form_for(@person) do |f|
      .error
        - if @person.errors.any?
          %h2 ERROR!
          %ul
            - @person.errors.full_messages.each do |msg|
              %li
                = msg

      .required
        = f.label :name
        = f.text_field :name
        = f.label :nickname
        = f.text_field :nickname, size: 16
        = f.label :reg
        = f.text_field :registration
      .readonly
        = 'Clinic: '+@person.clinic.to_s
      %div
        = f.label :year_of_birth
        = f.number_field :year_of_birth, :size => 4
      = f.label :male
      = f.check_box :male
      = f.label :fathers_name
      = f.text_field :fathers_name
      = f.label :reg_study
      = f.text_field :reg_study
      %div
        = f.label :remark
      %div
        = f.text_area :remark, :size => "80x4"
      - if not @person.name or @person.name == ''
        = f.label :village
        = f.text_field :village
      %div
        = f.submit "Update"
      %hr
      .readonly
        - if @person.created_at
          = @person.created_at.strftime("Created on %Y/%m/%d")
          = @person.updated_at.strftime(" and updated on %Y/%m/%d")

app/views/people/edit.html.erb
<h1>Editing person</h1>

<%= render 'form' %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/edit.html.haml
%h1 Patient card

%p
  = render 'form'
%p
  = link_to 'Show', @person
  |
  = link_to 'Back', people_path

app/views/people/index.html.erb
<h1>Search people</h1>

<table>
  <tr>
    <th>Registration</th>
    <th>Name</th>
    <th>Year of birth</th>
    <th>Gender</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @people.each do |person| %>
  <tr>
    <td><%= person.registration %></td>
    <td><%= person.name %></td>
    <td><%= person.year_of_birth %></td>
    <td><%= person.male %></td>
    <td><%= link_to 'Show', person %></td>
    <td><%= link_to 'Edit', edit_person_path(person) %></td>
    <td><%= link_to 'Destroy', person, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Person', new_person_path %>

app/views/people/index.html.haml
- [:notice, :error, :success].each do |key|
  - unless flash[key].blank?
    %p{ :class => "flash #{key}" }= flash[key] 

%p
  = form_tag people_path, :method => 'get' do
    %p
      = text_field_tag :search, params[:search] 
      = submit_tag "Search", :name => nil
    %p
      = check_box_tag :is_anywhere, true, params[:is_anywhere]
      = label_tag :is_anywhere, "match anywhere in name"
    // %p
    //  = label_tag :clinic_id, "Clinic"
    //  = text_field_tag :clinic_id, params[:clinic_id]
  = @people.size
  matches
  
.logo
  = link_to image_tag("Leprosy_PR_2010.jpg", :align => "right"),
    "http://www.who.int/lep/situation/en/"

%p
  %table
    %tr
      %th{ :align => :left} #
      %th{ :align => :left} Name
      %th Born
      %th Gender
      %th Village
      %th Clinic
    - @people.each do |person|
      %tr
        %td 
          = link_to person.registration, person
        %td 
          = link_to person.show_name, person
        %td 
          = person.year_of_birth
        %td 
          = (person.male ? 'M' : 'F')
        %td
          = person.village
        %td
          = person.clinic

        // <td><%= link_to 'Edit', edit_person_path(person) %></td>
        // <td><%= link_to 'Destroy', person, confirm: 'Are you sure?', method: :delete %></td>

%p
  Adjust search for more results
  = "(max. 100 results shown)" if @people.size > 70

app/views/people/new.html.erb
<h1>New person</h1>

<%= render 'form' %>

<%= link_to 'Back', people_path %>

app/views/people/new.html.haml
%h1
  New person

%p
  = render 'form'
  |
  = link_to 'Back', people_path

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Registration:</b>
  <%= @person.registration %>
</p>

<p>
  <b>Name:</b>
  <%= @person.name %>
</p>

<p>
  <b>Year of birth:</b>
  <%= @person.year_of_birth %>
</p>

<p>
  <b>Gender:</b>
  <%= @person.male %>
</p>


<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>

app/views/people/show.html.haml
%h1 
  = @person.show_name

%table
  %tr
    %td reg#
    %td
      = @person.registration
  %tr
    %td name
    %td 
      = @person.show_name
  %tr
    %td born
    %td 
      = @person.year_of_birth

  %tr
    %td gender
    %td 
      = @person.gender

  %tr
    %td village
    %td 
      = @person.village

  %tr
    %td clinic
    %td 
      = @person.clinic
%p
  = link_to 'Edit', edit_person_path(@person)
  |
  = link_to 'Back', people_path
%hr
%h3
  Personal history
  %ul
    - @person.personal_histories.each do |hist|
      %li
        = link_to hist.date.to_s + " (" + hist.id.to_s + ')', personal_history_path(hist)
    %li
      - if @person.personal_histories.size > 0
        = link_to 'Add new personal history', new_personal_history_path( copy_id: @person.personal_histories.last.id )
      - else
        = link_to 'First personal history', new_personal_history_path( person_id: @person.id )


%h3
  Contacts (medical history)
  %ul
    - @person.contacts.each do |c|
      %li
        = link_to c.date.to_s + ' (' + c.id.to_s + ')', contact_path(c)
    %li
      - if @person.contacts.size > 0
        = link_to 'Add new contact', new_contact_path( copy_id: @person.contacts.last.id )
      - else
        = link_to 'First contact', new_contact_path( person_id: @person.id )

%h3
  Assessments (examinations)
  %ul
    - @person.assessments.each do |a|
      %li
        = link_to a.date.to_s + ' (' + a.id.to_s + ')', assessment_path(a)
    %li
      - if @person.assessments.size > 0
        = link_to 'Add new assessment', new_assessment_path( copy_id: @person.assessments.last.id )
      - else
        = link_to 'First assessment', new_assessment_path( person_id: @person.id )

%h3
  Reactions
  %ul
    - @person.reactions.each do |a|
      %li
        = link_to a.date.to_s + ' (' + a.id.to_s + ')', reaction_path(a)
    %li
      - if @person.reactions.size > 0
        = link_to 'Add new reaction', new_reaction_path( copy_id: @person.reactions.last.id )
      - else
        = link_to 'First reaction', new_reaction_path( person_id: @person.id )

%h3
  Addresses
  %ul
    - @person.addresses.each do |a|
      %li
        - if a.village
          = link_to a.village + ' (' + a.id.to_s + ')', address_path(a)
        - else
          = link_to '(' + a.id.to_s + ')', address_path(a)
    %li
      = link_to 'Add new address', new_address_path( person_id: @person.id )