config/routes.rb
Lepra2::Application.routes.draw do
  get "lepra2/index"

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users, :controllers => { :registrations => "registrations" } 

  resources :symbol_lookups

  resources :assessments

  resources :reactions

  resources :staffs

  resources :clinics

  resources :contacts

  resources :personal_histories

  resources :people

  resources :remarks

  resources :locations

  resources :addresses

  root :to => 'lepra2#index'

end

app/models/remark.rb
class Remark < ActiveRecord::Base
end

app/controllers/remarks_controller.rb
class RemarksController < ApplicationController
  # GET /remarks
  # GET /remarks.json
  def index
    @remarks = Remark.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @remarks }
    end
  end

  # GET /remarks/1
  # GET /remarks/1.json
  def show
    @remark = Remark.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @remark }
    end
  end

  # GET /remarks/new
  # GET /remarks/new.json
  def new
    @remark = Remark.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @remark }
    end
  end

  # GET /remarks/1/edit
  def edit
    @remark = Remark.find(params[:id])
  end

  # POST /remarks
  # POST /remarks.json
  def create
    @remark = Remark.new(params[:remark])

    respond_to do |format|
      if @remark.save
        format.html { redirect_to @remark, notice: 'Remark was successfully created.' }
        format.json { render json: @remark, status: :created, location: @remark }
      else
        format.html { render action: "new" }
        format.json { render json: @remark.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /remarks/1
  # PUT /remarks/1.json
  def update
    @remark = Remark.find(params[:id])

    respond_to do |format|
      if @remark.update_attributes(params[:remark])
        format.html { redirect_to @remark, notice: 'Remark was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @remark.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /remarks/1
  # DELETE /remarks/1.json
  def destroy
    @remark = Remark.find(params[:id])
    @remark.destroy

    respond_to do |format|
      format.html { redirect_to remarks_url }
      format.json { head :ok }
    end
  end
end

app/helpers/remarks_helper.rb
module RemarksHelper
end

app/views/remarks/_form.html.erb
<%= form_for(@remark) do |f| %>
  <% if @remark.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@remark.errors.count, "error") %> prohibited this remark from being saved:</h2>

      <ul>
      <% @remark.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :reporter %><br />
    <%= f.number_field :reporter %>
  </div>
  <div class="field">
    <%= f.label :remark %><br />
    <%= f.text_area :remark %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/remarks/edit.html.erb
<h1>Editing remark</h1>

<%= render 'form' %>

<%= link_to 'Show', @remark %> |
<%= link_to 'Back', remarks_path %>

app/views/remarks/index.html.erb
<h1>Listing remarks</h1>

<table>
  <tr>
    <th>Reporter</th>
    <th>Remark</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @remarks.each do |remark| %>
  <tr>
    <td><%= remark.reporter %></td>
    <td><%= remark.remark %></td>
    <td><%= link_to 'Show', remark %></td>
    <td><%= link_to 'Edit', edit_remark_path(remark) %></td>
    <td><%= link_to 'Destroy', remark, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Remark', new_remark_path %>

app/views/remarks/new.html.erb
<h1>New remark</h1>

<%= render 'form' %>

<%= link_to 'Back', remarks_path %>

app/views/remarks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Reporter:</b>
  <%= @remark.reporter %>
</p>

<p>
  <b>Remark:</b>
  <%= @remark.remark %>
</p>


<%= link_to 'Edit', edit_remark_path(@remark) %> |
<%= link_to 'Back', remarks_path %>